spring:
  datasource:
    url: jdbc:h2:mem:jwtSecurity
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
